name: GVVOLLEY

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Questo consente la scrittura sul repository, incluso il push di tag e modifiche

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Usa la versione aggiornata

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Usa Node.js 20
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npm run build
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

    # Semantic Release: solo sui push su main, NON nelle pull request
    - name: Run Semantic Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Deploy solo su push su main
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4  # Usa la versione aggiornata
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
